### ISSUE TITLE
Kanban board project

### ISSUE THREAD

**Issue by notlfish** [notlfish/Dog-breeds#21]
[Kanban board project](https://github.com/notlfish/JavaScript-Capstone/projects/1).
This team has 2 members: @notlfish (Lucas - student B) and @Felipeg005 (Felipe - student A).

**Comment by AshakaE** [comment]
### Hi @notlfish  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
- [x] Please assign cards to team members, also remember to equally share cards with team member by points
_sample image_

![image](https://user-images.githubusercontent.com/67957533/132226703-4b77badf-133e-4be3-8326-9b349fa82ed6.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by notlfish** [comment]
We got confused about this! It's already updated.
